version: "3"
services:
  # db:
  #   image: postgres:13.3
  #   container_name: postgres
  #   environment:
  #     POSTGRES_DB: "${POSTGRES_DB}"
  #     POSTGRES_USER: "${POSTGRES_USER}"
  #     POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  #     PGDATA: "/var/lib/postgresql/data/pgdata"
  #   volumes:
  #     - ../2. Init Database:/docker-entrypoint-initdb.d
  #     - .:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  # adminer:
  #   container_name: adminer
  #   image: adminer
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:8080
  bot:
    environment:
      TELEGRAM_API_TOKEN: "${TELEGRAM_API_TOKEN}"
      SUPPORT_CHAT_ID: "${SUPPORT_CHAT_ID}"
      READY_FOR_PAY_CHAT_ID: "${READY_FOR_PAY_CHAT_ID}"
      MESSAGES_FILENAME: "${MESSAGES_FILENAME}"
    build: server/
    restart: always
    volumes:
      - ./server:/server
      - ./logs:/logs
    ports:
      - 5466:5466
    command: python3 main.py